openapi:
  title: Vaden API
  version: 1.0.0
  description: API gerada automaticamente pelo Vaden.

server:
  port: 8080
  host: localhost

storage:
  provider: firebase # opções: local, s3, firebase
  local:
    folder: "./uploads"
  s3:
    bucket: "meu-bucket"
    region: "us-east-1"
    accessKey: "sua_access_key"
    secretKey: "seu_secret_key"
  firebase:
    projectId: "vaden-storage-test"
    apiKey: "my_api"

database:
  provider: postgres
  mysql:
    host: "localhost"
    port: 5432
    database: "vaden_db"
    username: "vaden_user"
    password: "vaden_pass"

security:
  secret: AisuSijfdiflkDkldkeokdokDKodk
  tokenValidity: 3600
  refreshTokenValidity: 604800
  issuer: "vaden"
  audiences:
    - "vaden"
